#!/usr/bin/env python
"""Record manual WebGL texture fidelity review passes in the approved bank."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BANK = ROOT / "configs" / "synthetic_recipes" / "cashsnap_webgl_approved_texture_bank_v1.json"
DEFAULT_FRONT_ROWS = ROOT / "runs" / "cashsnap" / "texture_fidelity_review" / "texture_qa_front_v1" / "scan_vs_render_rows.csv"
DEFAULT_BACK_ROWS = ROOT / "runs" / "cashsnap" / "texture_fidelity_review" / "texture_qa_back_v1" / "scan_vs_render_rows.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bank", type=Path, default=DEFAULT_BANK, help="Approved texture-bank JSON to update.")
    parser.add_argument(
        "--review-rows",
        type=Path,
        nargs="+",
        default=[DEFAULT_FRONT_ROWS, DEFAULT_BACK_ROWS],
        help="scan_vs_render_rows.csv files generated by build_webgl_texture_fidelity_review.py.",
    )
    parser.add_argument("--reviewed-at", required=True, help="Manual review date to record, YYYY-MM-DD.")
    parser.add_argument(
        "--status",
        default="manual_pass_texture_qa_v1",
        help="Manual review status to write for each approved class/side texture.",
    )
    return parser.parse_args()


def resolve(path: Path) -> Path:
    return path if path.is_absolute() else ROOT / path


def repo_path(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT).as_posix())


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def review_artifacts(paths: list[Path]) -> dict[tuple[str, str], str]:
    artifacts: dict[tuple[str, str], str] = {}
    for path in paths:
        resolved = resolve(path)
        for row in read_csv(resolved):
            class_name = row.get("class_name", "")
            side = row.get("side", "")
            pair_card = Path(row.get("pair_card", ""))
            if not class_name or not side or not pair_card:
                continue
            if not pair_card.is_absolute():
                pair_card = ROOT / pair_card
            if not pair_card.exists():
                raise SystemExit(f"missing pair card for {class_name}/{side}: {pair_card}")
            artifacts[(class_name, side)] = repo_path(pair_card)
    return artifacts


def main() -> int:
    args = parse_args()
    bank_path = resolve(args.bank)
    payload = read_json(bank_path)
    artifacts = review_artifacts(args.review_rows)
    missing: list[str] = []
    for row in payload.get("rows", []):
        key = (row.get("class_name", ""), row.get("side", ""))
        artifact = artifacts.get(key)
        if not artifact:
            missing.append("/".join(key))
            continue
        row["visual_review_status"] = args.status
        row["visual_review_artifact"] = artifact
        row["visual_review_notes"] = (
            "Raw-vs-render pair card reviewed; visible crop/scan marks are source texture artifacts, "
            "not renderer-added."
        )
        row["visual_reviewed_at"] = args.reviewed_at

    if missing:
        raise SystemExit(f"missing pair review rows: {', '.join(missing)}")

    payload["visual_review"] = {
        "status": args.status,
        "reviewed_at": args.reviewed_at,
        "scope": "all approved latest-design in-circulation class/side textures",
        "class_side_count": len(payload.get("rows", [])),
        "method": "manual raw-source versus WebGL texture_qa scan_fidelity pair-card review, crop_pad=0",
        "render_roots": {
            "front": "data/synthetic/cashsnap_webgl_texture_qa_front_v1",
            "back": "data/synthetic/cashsnap_webgl_texture_qa_back_v1",
        },
        "review_dirs": {
            "front": "runs/cashsnap/texture_fidelity_review/texture_qa_front_v1/pairs",
            "back": "runs/cashsnap/texture_fidelity_review/texture_qa_back_v1/pairs",
        },
        "known_source_caveats": [
            "Several KHR source scans include edge bands or scan/crop softness that are visible in the raw pair card and preserved in render.",
            "USD_50_back has a tiny dark lower-left source crop line visible in the raw pair card.",
            "USD_100_back has small source top-edge specks visible in the raw pair card.",
        ],
    }
    bank_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"updated {repo_path(bank_path)} with {len(payload.get('rows', []))} reviewed textures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
